### PR TITLE
engine: Open lru cache and memtable size of rocskdb

### PR DESCRIPTION
**Pull request by uran0sH**

### CODE REVIEW

**Comment by luanshaotong** [comment]
How's the performance about this?

**Comment by uran0sH** [comment]
> How's the performance about this?

@Tricky511 Do you have time to bench it using IO500?

**Comment by Tricky511** [comment]
> > How's the performance about this?
> 
> @Tricky511 Do you have time to bench it using IO500?

I'll take a test

**Comment by Tricky511** [comment]
@uran0sH Cannot put an expression as a number
image

**Comment by Tricky511** [comment]
> > How's the performance about this?
> 
> @Tricky511 Do you have time to bench it using IO500?

I measured the difference on a machine is not much
image
image

**Comment by Tricky511** [comment]
I think open should not be a bottleneck at the moment, can not see whether there is an improvement

**Comment by uran0sH** [comment]
> > > How's the performance about this?
> > 
> > 
> > @Tricky511 Do you have time to bench it using IO500?
> 
> I measured the difference on a machine is not much
> 
> cache: image no cache image

You can change the cache capacity to the memory's max size.

**Comment by Tricky511** [comment]
> > > > How's the performance about this?
> > > 
> > > 
> > > @Tricky511 Do you have time to bench it using IO500?
> > 
> > 
> > I measured the difference on a machine is not much
> > cache: image no cache image
> 
> You can change the cache capacity to the memory's max size.

Change to 4GB, no gap
image

**Review by luanshaotong — APPROVED** [review]
LGTM. Pls fix the conflict.

**Pull request merged**
