### PR TITLE
engine: Add main-memory KV storage

### PR DESCRIPTION
**Pull request by uran0sH**

### CODE REVIEW

**Comment by luanshaotong** [comment]
Look good to me. Next, we need to split every attribute of file. This will change the interface of meta data db.

**Review by luanshaotong — APPROVED** [review]

**Comment by uran0sH** [comment]
> Can you leave an option to use rocksdb?

What do you mean? Now we can both use rocksdb and mem-kv.

**Comment by luanshaotong** [comment]
> > Can you leave an option to use rocksdb?
> 
> What do you mean? Now we can both use rocksdb and mem-kv.

Sorry it was my mistake.

**Comment by Tricky511** [comment]
I think we need to avoid serialization, can this be done?

**Comment by uran0sH** [comment]
> I think we need to avoid serialization, can this be done?

I am working on it.

**Pull request merged**
